language: python

python:
  - "3.5"
  - "3.6"

install:
  - pip install -e .[deploy]

script:
  - pytest

before_deploy:
  - "if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then make apidoc; make html;fi"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: false
  local_dir: docs/_build/html
  on:
    branch: master
    python: 3.5